<table id="calcTB" class="calcTB">
	<tr><td colspan="4" id="calcDisplay" class="calcDisplay">Display</td></tr>
	<tr>
		<td><button>$$x^n$$</button></td>
		<td><button>$$CE$$</button></td>
		<td><button>$$C$$</button></td>
		<td><button>$$\div$$</button></td>
	</tr>
	<tr>
		<td><button>$$7$$</button></td>
		<td><button>$$8$$</button></td>
		<td><button>$$9$$</button></td>
		<td><button>$$\times$$</button></td>
	</tr>
	<tr>
		<td><button>$$4$$</button></td>
		<td><button>$$5$$</button></td>
		<td><button>$$6$$</button></td>
		<td><button>$$-$$</button></td>
	</tr>
	<tr>
		<td><button>$$1$$</button></td>
		<td><button>$$2$$</button></td>
		<td><button>$$3$$</button></td>
		<td><button>$$+$$</button></td>
	</tr>
	<tr>
		<td><button>$$(-)$$</button></td>
		<td><button>$$0$$</button></td>
		<td><button>$$.$$</button></td>
		<td><button>$$=$$</button></td>
	</tr>
</table>